backend:
  name: github
  repo: jamesrharwood/srqr
  site_domain: https://jamesrharwood.github.io/equator-guidelines-website/guidelines/srqr/
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: netlify-cms/
  branch: master # Branch to update (optional; defaults to master)
media_folder: "uploads" # Media files will be stored in the repo under /uploads
collections:
  - name: "item" # Used in routes, e.g., /admin/collections/blog
    label: "Reporting Item" # Used in the UI
    folder: "_items" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{id}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Read More", name: "read_more", widget: "markdown"}

    
  
