backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: uploads/
collections:
  - name: pages
    label: Pages
    delete: false
    files:
      - label: Readme
        name: Readme
        file: README.md
        fields: 
          - name: body
            label: Body
            widget: markdown

